let DSA = [];
let PL = [];
let Networks = [];

while (true) {
  let subjectChoice = prompt("Select a subject to enroll:\n(A) DSA\n(B) PL\n(C) Networks");
  if (subjectChoice.toUpperCase() === 'A') {
      let operationChoice = prompt("Select an operation:\n(A) Enroll\n(B) Unenroll\n(C) Select Another Subject\n(D) Exit");
          if (operationChoice.toUpperCase() === 'A') {
                let studentName = prompt("Enter the name of the student to enroll:");
                      DSA.push(studentName);
                            console.log(`${studentName} enrolled in DSA.`);
                                } else if (operationChoice.toUpperCase() === 'B') {
                                      if (DSA.length === 0) {
                                              console.log("No students are enrolled in DSA.");
                                                    } else {
                                                            console.log("Currently enrolled students in DSA:");
                                                                    for (let i = 0; i < DSA.length; i++) {
                                                                              console.log(`${i + 1}. ${DSA[i]}`);
                                                                                      }
                                                                                              let studentName = prompt("Enter the name of the student to unenroll:");
                                                                                                      let index = DSA.indexOf(studentName);
                                                                                                              if (index !== -1) {
                                                                                                                        DSA.splice(index, 1);
                                                                                                                                  console.log(`${studentName} unenrolled from DSA.`);
                                                                                                                                          } else {
                                                                                                                                                    console.log(`${studentName} is not enrolled in DSA.`);
                                                                                                                                                            }
                                                                                                                                                                  }
                                                                                                                                                                      } else if (operationChoice.toUpperCase() === 'C') {
                                                                                                                                                                            continue;
                                                                                                                                                                                } else if (operationChoice.toUpperCase() === 'D') {
                                                                                                                                                                                      break;
                                                                                                                                                                                          } else {
                                                                                                                                                                                                console.log("Invalid operation choice.");
                                                                                                                                                                                                    }
                                                                                                                                                                                                      } else if (subjectChoice.toUpperCase() === 'B') {
                                                                                                                                                                                                          let operationChoice = prompt("Select an operation:\n(A) Enroll\n(B) Unenroll\n(C) Select Another Subject\n(D) Exit");
                                                                                                                                                                                                              if (operationChoice.toUpperCase() === 'A') {
                                                                                                                                                                                                                    let studentName = prompt("Enter the name of the student to enroll:");
                                                                                                                                                                                                                          PL.push(studentName);
                                                                                                                                                                                                                                console.log(`${studentName} enrolled in PL.`);
                                                                                                                                                                                                                                    } else if (operationChoice.toUpperCase() === 'B') {
                                                                                                                                                                                                                                          if (PL.length === 0) {
                                                                                                                                                                                                                                                  console.log("No students are enrolled in PL.");
                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                console.log("Currently enrolled students in PL:");
                                                                                                                                                                                                                                                                        for (let i = 0; i < PL.length; i++) {
                                                                                                                                                                                                                                                                                  console.log(`${i + 1}. ${PL[i]}`);
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                  let studentName = prompt("Enter the name of the student to unenroll:");
                                                                                                                                                                                                                                                                                                          let index = PL.indexOf(studentName);
                                                                                                                                                                                                                                                                                                                  if (index !== -1) {
                                                                                                                                                                                                                                                                                                                            PL.splice(index, 1);
                                                                                                                                                                                                                                                                                                                                      console.log(`${studentName} unenrolled from PL.`);
                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                        console.log(`${studentName} is not enrolled in PL.`);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                          } else if (operationChoice.toUpperCase() === 'C') {
                                                                                                                                                                                                                                                                                                                                                                                continue;
                                                                                                                                                                                                                                                                                                                                                                                    } else if (operationChoice.toUpperCase() === 'D') {
                                                                                                                                                                                                                                                                                                                                                                                          break;
                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                    console.log("Invalid operation choice.");
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                          } else if (subjectChoice.toUpperCase() === 'C') {
                                                                                                                                                                                                                                                                                                                                                                                                              let operationChoice = prompt("Select an operation:\n(A) Enroll\n(B) Unenroll\n(C) Select Another Subject\n(D) Exit");
                                                                                                                                                                                                                                                                                                                                                                                                                  if (operationChoice.toUpperCase() === 'A') {
                                                                                                                                                                                                                                                                                                                                                                                                                        let studentName = prompt("Enter the name of the student to enroll:");
                                                                                                                                                                                                                                                                                                                                                                                                                              Networks.push(studentName);
                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`${studentName} enrolled in Networks.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (operationChoice.to
                                   
